class Language:
    TR = {
        "title": "AI Süreç Yöneticisi",
        "search_placeholder": "🔍 İşlem Ara...",
        "col_pid": "PID",
        "col_name": "İsim",
        "col_mem": "Bellek (MB)",
        "detail_title": "İşlem Detayı",
        "api_btn": "⚙️ API",
        "api_title": "Gemini API Ayarları",
        "api_label": "Google Gemini API Anahtarınızı Girin:",
        "api_save": "Kaydet",
        "api_success": "API Anahtarı Başarıyla Kaydedildi!",
        "api_missing": "Lütfen bir anahtar girin.",
        "api_required_title": "API Anahtarı Gerekli",
        "api_required_msg": "Analiz yapmak için Gemini API Anahtarı girmelisiniz.\nŞimdi eklemek ister misiniz?",
        "api_saved": "Kayıtlı",
        "reanalyze_btn": "Yeniden Analiz (AI)",
        "pid": "PID: -",
        "name": "Ad: -",
        "memory": "Bellek: -",
        "analyze_btn": "✨ Analiz Et",
        "folder_btn": "📂 Dosya Konumu",
        "kill_btn": "💀 Sonlandır",
        "error_select": "Lütfen önce listeden bir işlem seçin.",
        "loading": "⏳ Dosya Hash'i hesaplanıyor ve AI analizi yapılıyor...\nLütfen bekleyin...",
        "error_list": "İşlem listede bulunamadı. Lütfen listeyi yenileyin.",
        "analyzing": "1. İşlem detayları (Path/İmza) alınıyor...",
        "analyzing_2": "2. Analiz Yapılıyor (Veritabanı/AI)...",
        "analyzing_3": "3. AI Analizi tamamlandı.",
        "card_identity": "📋 Kimlik Kartı",
        "card_risk": "🛡️ Risk Skoru",
        "card_security": "🔍 Güvenlik Analizi",
        "card_memory": "🧠 Bellek Analizi",
        "card_result": "🏁 Sonuç",
        "confirm_kill": "{0} (PID: {1}) işlemini sonlandırmak istediğinize emin misiniz?",
        "success_kill": "İşlem sonlandırıldı.",
        "error_path": "Dosya yolu bulunamadı veya erişilemiyor.",
        "start_msg": "Analiz için 'Analiz Et' butonuna basınız.\nDosya hash'i hesaplanacak ve taranacaktır."
    }

    EN = {
        "title": "AI Process Manager",
        "search_placeholder": "🔍 Search Process...",
        "col_pid": "PID",
        "col_name": "Name",
        "col_mem": "Memory (MB)",
        "detail_title": "Process Details",
        "api_btn": "⚙️ API",
        "api_title": "Gemini API Settings",
        "api_label": "Enter Google Gemini API Key:",
        "api_save": "Save",
        "api_success": "API Key Saved Successfully!",
        "api_missing": "Please enter a key.",
        "api_required_title": "API Key Required",
        "api_required_msg": "You must enter a Gemini API Key to perform analysis.\nDo you want to add it now?",
        "api_saved": "Saved",
        "reanalyze_btn": "Re-Analyze (AI)",
        "pid": "PID: -",
        "name": "Name: -",
        "memory": "Memory: -",
        "analyze_btn": "✨ Analyze",
        "folder_btn": "📂 Open Location",
        "kill_btn": "💀 Kill Process",
        "error_select": "Please select a process from the list first.",
        "loading": "⏳ Calculating File Hash and Analyzing with AI...\nPlease wait...",
        "error_list": "Process not found in list. Please refresh.",
        "analyzing": "1. Getting Process Details (Path/Signature)...",
        "analyzing_2": "2. Analyzing (Database/AI)...",
        "analyzing_3": "3. AI Analysis Completed.",
        "card_identity": "📋 Identity Card",
        "card_risk": "🛡️ Risk Score",
        "card_security": "🔍 Security Analysis",
        "card_memory": "🧠 Memory Analysis",
        "card_result": "🏁 Result",
        "confirm_kill": "Are you sure you want to terminate {0} (PID: {1})?",
        "success_kill": "Process terminated.",
        "error_path": "File path not found or inaccessible.",
        "start_msg": "Click 'Analyze' button to start.\nFile hash will be calculated and scanned."
    }
